### ISSUE TITLE
Could you upload scene files for TestProject please?The TestProject can not run.

### ISSUE THREAD

**Issue by luoyan988** [JulianThijssen/Flux#17]

**Comment by JulianThijssen** [comment]
I don't really want to post models on the github, but I can send you a test scene.

**Comment by qjh5606** [comment]
> .

Can you send me a test scene. My e-mail is chenjz1993@qq.com

**Comment by qjh5606** [comment]
@JulianThijssen Can you send me a test scene. My e-mail is chenjz1993@qq.com

**Comment by JulianThijssen** [comment]
Test scene is now available via a link in the README.
